### ISSUE TITLE
Incomplete type error

### ISSUE THREAD

**Issue by larsmaxwell** [MakeSchool/GameOfLife-Cpp#2]
I am seeing an error:

`Incomplete type 'Creature' named in nested name specifier.`

when I try to define creature in the loop here:

```c++
    for (int row = 0; row < ROWS; ++row)
    {
        for (int col = 0; col < COLUMNS; ++col)
        {
            Creature* creature = Creature::create();
            
            creature->setAnchorPoint(Vec2(0.0f, 0.0f));
            creature->setPosition(cellWidth *  float(col), cellHeight * float(row));
            
            gridSprite->addChild(creature);
            
            gridArray.pushBack(creature);
        }
    }
```

on the line

`Creature* creature = Creature::create();`

Does this need to be defined in the .hpp file for this class? I know that the version I am using is the most recent but if you could maybe help me clue in why I am seeing this error in the editor or point me in the right direction. I am new to c++ and still learning the rules

**Comment by danielhaaser** [comment]
Yeah, you should import Creature in your header file.

Make sure you have this in your Grid.hpp (or Grid.h):
```cpp
#include "cocos2d.h"
#include "Creature.h"
```

If your Creature.h file is instead named Creature.hpp, you should change the code to `#include "Creature.hpp"`

**Comment by larsmaxwell** [comment]
It's weird, and I don't know why, but when I change the file type to regular header .h type and reference it in the #include, the Class `<Creature*>` is now available.

Is there something about the .hpp type that would make the `#include` not work?

**Comment by danielhaaser** [comment]
Hmm, I would think it would work with .hpp assuming that you had `#include "Creature.hpp"` - if it didn't then I'm not really sure what's going on.
